name: cars12

#on:
  #schedule:
   # - cron: "10 10 * * *"
  #push: 

    

jobs:
  RunScript:
    runs-on: ubuntu-latest
    concurrency: my-concurrency-group3jddt
    timeout-minutes: 4000

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4
          pip install pyodbc
          pip install regex
          pip install lxml
          pip install requests
          pip install GitPython
          pip install pandas
          pip install pyyaml
          pip install regex 
          pip install azure-storage-blob
          pip install pandas 
          pip install aiohttp 
          pip install asyncio 
          pip install aiohttp_proxy

      - name: Run cars.py
        run: python cars.py
     
